FROM alpine:latest
RUN apk add --no-cache ca-certificates tzdata
# 拷贝编译好的二进制
COPY v2raya_arm64 /usr/bin/v2raya
RUN chmod +x /usr/bin/v2raya
EXPOSE 2017
# 官方默认数据目录
VOLUME /etc/v2raya
ENTRYPOINT ["v2raya"]
