FROM --platform=linux/arm64 alpine:latest
RUN apk add --no-cache ca-certificates tzdata
# 将 Action 编译好的二进制和前端文件拷入
COPY v2raya_arm64 /usr/bin/v2raya
COPY web_files /etc/v2raya/web
EXPOSE 2017
ENTRYPOINT ["v2raya"]
